// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: orderbook.proto

#ifndef PROTOBUF_INCLUDED_orderbook_2eproto
#define PROTOBUF_INCLUDED_orderbook_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "shared.pb.h"
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_orderbook_2eproto 

namespace protobuf_orderbook_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_orderbook_2eproto
namespace proto {
class OrderBookProto;
class OrderBookProtoDefaultTypeInternal;
extern OrderBookProtoDefaultTypeInternal _OrderBookProto_default_instance_;
}  // namespace proto
namespace google {
namespace protobuf {
template<> ::proto::OrderBookProto* Arena::CreateMaybeMessage<::proto::OrderBookProto>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace proto {

// ===================================================================

class OrderBookProto : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.OrderBookProto) */ {
 public:
  OrderBookProto();
  virtual ~OrderBookProto();

  OrderBookProto(const OrderBookProto& from);

  inline OrderBookProto& operator=(const OrderBookProto& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  OrderBookProto(OrderBookProto&& from) noexcept
    : OrderBookProto() {
    *this = ::std::move(from);
  }

  inline OrderBookProto& operator=(OrderBookProto&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const OrderBookProto& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const OrderBookProto* internal_default_instance() {
    return reinterpret_cast<const OrderBookProto*>(
               &_OrderBookProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(OrderBookProto* other);
  friend void swap(OrderBookProto& a, OrderBookProto& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline OrderBookProto* New() const final {
    return CreateMaybeMessage<OrderBookProto>(NULL);
  }

  OrderBookProto* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<OrderBookProto>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const OrderBookProto& from);
  void MergeFrom(const OrderBookProto& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(OrderBookProto* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .proto.PricePointProto points = 4;
  int points_size() const;
  void clear_points();
  static const int kPointsFieldNumber = 4;
  ::proto::PricePointProto* mutable_points(int index);
  ::google::protobuf::RepeatedPtrField< ::proto::PricePointProto >*
      mutable_points();
  const ::proto::PricePointProto& points(int index) const;
  ::proto::PricePointProto* add_points();
  const ::google::protobuf::RepeatedPtrField< ::proto::PricePointProto >&
      points() const;

  // string market = 1;
  void clear_market();
  static const int kMarketFieldNumber = 1;
  const ::std::string& market() const;
  void set_market(const ::std::string& value);
  #if LANG_CXX11
  void set_market(::std::string&& value);
  #endif
  void set_market(const char* value);
  void set_market(const char* value, size_t size);
  ::std::string* mutable_market();
  ::std::string* release_market();
  void set_allocated_market(::std::string* market);

  // .proto.SpreadProto spread = 3;
  bool has_spread() const;
  void clear_spread();
  static const int kSpreadFieldNumber = 3;
  private:
  const ::proto::SpreadProto& _internal_spread() const;
  public:
  const ::proto::SpreadProto& spread() const;
  ::proto::SpreadProto* release_spread();
  ::proto::SpreadProto* mutable_spread();
  void set_allocated_spread(::proto::SpreadProto* spread);

  // uint64 size = 2;
  void clear_size();
  static const int kSizeFieldNumber = 2;
  ::google::protobuf::uint64 size() const;
  void set_size(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:proto.OrderBookProto)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::proto::PricePointProto > points_;
  ::google::protobuf::internal::ArenaStringPtr market_;
  ::proto::SpreadProto* spread_;
  ::google::protobuf::uint64 size_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_orderbook_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// OrderBookProto

// string market = 1;
inline void OrderBookProto::clear_market() {
  market_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& OrderBookProto::market() const {
  // @@protoc_insertion_point(field_get:proto.OrderBookProto.market)
  return market_.GetNoArena();
}
inline void OrderBookProto::set_market(const ::std::string& value) {
  
  market_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:proto.OrderBookProto.market)
}
#if LANG_CXX11
inline void OrderBookProto::set_market(::std::string&& value) {
  
  market_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:proto.OrderBookProto.market)
}
#endif
inline void OrderBookProto::set_market(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  market_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:proto.OrderBookProto.market)
}
inline void OrderBookProto::set_market(const char* value, size_t size) {
  
  market_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:proto.OrderBookProto.market)
}
inline ::std::string* OrderBookProto::mutable_market() {
  
  // @@protoc_insertion_point(field_mutable:proto.OrderBookProto.market)
  return market_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* OrderBookProto::release_market() {
  // @@protoc_insertion_point(field_release:proto.OrderBookProto.market)
  
  return market_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void OrderBookProto::set_allocated_market(::std::string* market) {
  if (market != NULL) {
    
  } else {
    
  }
  market_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), market);
  // @@protoc_insertion_point(field_set_allocated:proto.OrderBookProto.market)
}

// uint64 size = 2;
inline void OrderBookProto::clear_size() {
  size_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 OrderBookProto::size() const {
  // @@protoc_insertion_point(field_get:proto.OrderBookProto.size)
  return size_;
}
inline void OrderBookProto::set_size(::google::protobuf::uint64 value) {
  
  size_ = value;
  // @@protoc_insertion_point(field_set:proto.OrderBookProto.size)
}

// .proto.SpreadProto spread = 3;
inline bool OrderBookProto::has_spread() const {
  return this != internal_default_instance() && spread_ != NULL;
}
inline const ::proto::SpreadProto& OrderBookProto::_internal_spread() const {
  return *spread_;
}
inline const ::proto::SpreadProto& OrderBookProto::spread() const {
  const ::proto::SpreadProto* p = spread_;
  // @@protoc_insertion_point(field_get:proto.OrderBookProto.spread)
  return p != NULL ? *p : *reinterpret_cast<const ::proto::SpreadProto*>(
      &::proto::_SpreadProto_default_instance_);
}
inline ::proto::SpreadProto* OrderBookProto::release_spread() {
  // @@protoc_insertion_point(field_release:proto.OrderBookProto.spread)
  
  ::proto::SpreadProto* temp = spread_;
  spread_ = NULL;
  return temp;
}
inline ::proto::SpreadProto* OrderBookProto::mutable_spread() {
  
  if (spread_ == NULL) {
    auto* p = CreateMaybeMessage<::proto::SpreadProto>(GetArenaNoVirtual());
    spread_ = p;
  }
  // @@protoc_insertion_point(field_mutable:proto.OrderBookProto.spread)
  return spread_;
}
inline void OrderBookProto::set_allocated_spread(::proto::SpreadProto* spread) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(spread_);
  }
  if (spread) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      spread = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, spread, submessage_arena);
    }
    
  } else {
    
  }
  spread_ = spread;
  // @@protoc_insertion_point(field_set_allocated:proto.OrderBookProto.spread)
}

// repeated .proto.PricePointProto points = 4;
inline int OrderBookProto::points_size() const {
  return points_.size();
}
inline ::proto::PricePointProto* OrderBookProto::mutable_points(int index) {
  // @@protoc_insertion_point(field_mutable:proto.OrderBookProto.points)
  return points_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::proto::PricePointProto >*
OrderBookProto::mutable_points() {
  // @@protoc_insertion_point(field_mutable_list:proto.OrderBookProto.points)
  return &points_;
}
inline const ::proto::PricePointProto& OrderBookProto::points(int index) const {
  // @@protoc_insertion_point(field_get:proto.OrderBookProto.points)
  return points_.Get(index);
}
inline ::proto::PricePointProto* OrderBookProto::add_points() {
  // @@protoc_insertion_point(field_add:proto.OrderBookProto.points)
  return points_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::proto::PricePointProto >&
OrderBookProto::points() const {
  // @@protoc_insertion_point(field_list:proto.OrderBookProto.points)
  return points_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace proto

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_orderbook_2eproto
