// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shared.proto

#include "shared.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace proto {
class MarketRequestProtoDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<MarketRequestProto>
      _instance;
} _MarketRequestProto_default_instance_;
class PricePointProtoDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<PricePointProto>
      _instance;
} _PricePointProto_default_instance_;
class SpreadProtoDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<SpreadProto>
      _instance;
} _SpreadProto_default_instance_;
class UUIDDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<UUID>
      _instance;
} _UUID_default_instance_;
}  // namespace proto
namespace protobuf_shared_2eproto {
static void InitDefaultsMarketRequestProto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::proto::_MarketRequestProto_default_instance_;
    new (ptr) ::proto::MarketRequestProto();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::proto::MarketRequestProto::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_MarketRequestProto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsMarketRequestProto}, {}};

static void InitDefaultsPricePointProto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::proto::_PricePointProto_default_instance_;
    new (ptr) ::proto::PricePointProto();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::proto::PricePointProto::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_PricePointProto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsPricePointProto}, {}};

static void InitDefaultsSpreadProto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::proto::_SpreadProto_default_instance_;
    new (ptr) ::proto::SpreadProto();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::proto::SpreadProto::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_SpreadProto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsSpreadProto}, {}};

static void InitDefaultsUUID() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::proto::_UUID_default_instance_;
    new (ptr) ::proto::UUID();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::proto::UUID::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_UUID =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsUUID}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_MarketRequestProto.base);
  ::google::protobuf::internal::InitSCC(&scc_info_PricePointProto.base);
  ::google::protobuf::internal::InitSCC(&scc_info_SpreadProto.base);
  ::google::protobuf::internal::InitSCC(&scc_info_UUID.base);
}

::google::protobuf::Metadata file_level_metadata[4];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::proto::MarketRequestProto, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::proto::MarketRequestProto, market_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::proto::PricePointProto, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::proto::PricePointProto, price_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::proto::PricePointProto, depth_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::proto::PricePointProto, side_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::proto::SpreadProto, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::proto::SpreadProto, spread_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::proto::UUID, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::proto::UUID, uuid_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::proto::MarketRequestProto)},
  { 6, -1, sizeof(::proto::PricePointProto)},
  { 14, -1, sizeof(::proto::SpreadProto)},
  { 20, -1, sizeof(::proto::UUID)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::proto::_MarketRequestProto_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::proto::_PricePointProto_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::proto::_SpreadProto_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::proto::_UUID_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "shared.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 4);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\014shared.proto\022\005proto\"$\n\022MarketRequestPr"
      "oto\022\016\n\006market\030\001 \001(\t\"U\n\017PricePointProto\022\r"
      "\n\005price\030\001 \001(\004\022\r\n\005depth\030\002 \001(\004\022$\n\004side\030\003 \001"
      "(\0162\026.proto.MarketSideProto\"\035\n\013SpreadProt"
      "o\022\016\n\006spread\030\001 \001(\002\"\024\n\004UUID\022\014\n\004UUID\030\001 \001(\t*"
      "#\n\017MarketSideProto\022\007\n\003BID\020\000\022\007\n\003ASK\020\001b\006pr"
      "oto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 244);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "shared.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_shared_2eproto
namespace proto {
const ::google::protobuf::EnumDescriptor* MarketSideProto_descriptor() {
  protobuf_shared_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_shared_2eproto::file_level_enum_descriptors[0];
}
bool MarketSideProto_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}


// ===================================================================

void MarketRequestProto::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int MarketRequestProto::kMarketFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

MarketRequestProto::MarketRequestProto()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_shared_2eproto::scc_info_MarketRequestProto.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:proto.MarketRequestProto)
}
MarketRequestProto::MarketRequestProto(const MarketRequestProto& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  market_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.market().size() > 0) {
    market_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.market_);
  }
  // @@protoc_insertion_point(copy_constructor:proto.MarketRequestProto)
}

void MarketRequestProto::SharedCtor() {
  market_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

MarketRequestProto::~MarketRequestProto() {
  // @@protoc_insertion_point(destructor:proto.MarketRequestProto)
  SharedDtor();
}

void MarketRequestProto::SharedDtor() {
  market_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void MarketRequestProto::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* MarketRequestProto::descriptor() {
  ::protobuf_shared_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_shared_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const MarketRequestProto& MarketRequestProto::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_shared_2eproto::scc_info_MarketRequestProto.base);
  return *internal_default_instance();
}


void MarketRequestProto::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.MarketRequestProto)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  market_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool MarketRequestProto::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:proto.MarketRequestProto)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string market = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_market()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->market().data(), static_cast<int>(this->market().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "proto.MarketRequestProto.market"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:proto.MarketRequestProto)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:proto.MarketRequestProto)
  return false;
#undef DO_
}

void MarketRequestProto::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:proto.MarketRequestProto)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string market = 1;
  if (this->market().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->market().data(), static_cast<int>(this->market().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "proto.MarketRequestProto.market");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->market(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:proto.MarketRequestProto)
}

::google::protobuf::uint8* MarketRequestProto::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:proto.MarketRequestProto)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string market = 1;
  if (this->market().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->market().data(), static_cast<int>(this->market().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "proto.MarketRequestProto.market");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->market(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto.MarketRequestProto)
  return target;
}

size_t MarketRequestProto::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:proto.MarketRequestProto)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string market = 1;
  if (this->market().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->market());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void MarketRequestProto::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:proto.MarketRequestProto)
  GOOGLE_DCHECK_NE(&from, this);
  const MarketRequestProto* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const MarketRequestProto>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:proto.MarketRequestProto)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:proto.MarketRequestProto)
    MergeFrom(*source);
  }
}

void MarketRequestProto::MergeFrom(const MarketRequestProto& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:proto.MarketRequestProto)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.market().size() > 0) {

    market_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.market_);
  }
}

void MarketRequestProto::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:proto.MarketRequestProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MarketRequestProto::CopyFrom(const MarketRequestProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:proto.MarketRequestProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MarketRequestProto::IsInitialized() const {
  return true;
}

void MarketRequestProto::Swap(MarketRequestProto* other) {
  if (other == this) return;
  InternalSwap(other);
}
void MarketRequestProto::InternalSwap(MarketRequestProto* other) {
  using std::swap;
  market_.Swap(&other->market_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata MarketRequestProto::GetMetadata() const {
  protobuf_shared_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_shared_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void PricePointProto::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PricePointProto::kPriceFieldNumber;
const int PricePointProto::kDepthFieldNumber;
const int PricePointProto::kSideFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PricePointProto::PricePointProto()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_shared_2eproto::scc_info_PricePointProto.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:proto.PricePointProto)
}
PricePointProto::PricePointProto(const PricePointProto& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&price_, &from.price_,
    static_cast<size_t>(reinterpret_cast<char*>(&side_) -
    reinterpret_cast<char*>(&price_)) + sizeof(side_));
  // @@protoc_insertion_point(copy_constructor:proto.PricePointProto)
}

void PricePointProto::SharedCtor() {
  ::memset(&price_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&side_) -
      reinterpret_cast<char*>(&price_)) + sizeof(side_));
}

PricePointProto::~PricePointProto() {
  // @@protoc_insertion_point(destructor:proto.PricePointProto)
  SharedDtor();
}

void PricePointProto::SharedDtor() {
}

void PricePointProto::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* PricePointProto::descriptor() {
  ::protobuf_shared_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_shared_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const PricePointProto& PricePointProto::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_shared_2eproto::scc_info_PricePointProto.base);
  return *internal_default_instance();
}


void PricePointProto::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.PricePointProto)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&price_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&side_) -
      reinterpret_cast<char*>(&price_)) + sizeof(side_));
  _internal_metadata_.Clear();
}

bool PricePointProto::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:proto.PricePointProto)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint64 price = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &price_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint64 depth = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &depth_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .proto.MarketSideProto side = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_side(static_cast< ::proto::MarketSideProto >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:proto.PricePointProto)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:proto.PricePointProto)
  return false;
#undef DO_
}

void PricePointProto::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:proto.PricePointProto)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 price = 1;
  if (this->price() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(1, this->price(), output);
  }

  // uint64 depth = 2;
  if (this->depth() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(2, this->depth(), output);
  }

  // .proto.MarketSideProto side = 3;
  if (this->side() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      3, this->side(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:proto.PricePointProto)
}

::google::protobuf::uint8* PricePointProto::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:proto.PricePointProto)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 price = 1;
  if (this->price() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(1, this->price(), target);
  }

  // uint64 depth = 2;
  if (this->depth() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(2, this->depth(), target);
  }

  // .proto.MarketSideProto side = 3;
  if (this->side() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      3, this->side(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto.PricePointProto)
  return target;
}

size_t PricePointProto::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:proto.PricePointProto)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // uint64 price = 1;
  if (this->price() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->price());
  }

  // uint64 depth = 2;
  if (this->depth() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->depth());
  }

  // .proto.MarketSideProto side = 3;
  if (this->side() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->side());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void PricePointProto::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:proto.PricePointProto)
  GOOGLE_DCHECK_NE(&from, this);
  const PricePointProto* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const PricePointProto>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:proto.PricePointProto)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:proto.PricePointProto)
    MergeFrom(*source);
  }
}

void PricePointProto::MergeFrom(const PricePointProto& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:proto.PricePointProto)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.price() != 0) {
    set_price(from.price());
  }
  if (from.depth() != 0) {
    set_depth(from.depth());
  }
  if (from.side() != 0) {
    set_side(from.side());
  }
}

void PricePointProto::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:proto.PricePointProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PricePointProto::CopyFrom(const PricePointProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:proto.PricePointProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PricePointProto::IsInitialized() const {
  return true;
}

void PricePointProto::Swap(PricePointProto* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PricePointProto::InternalSwap(PricePointProto* other) {
  using std::swap;
  swap(price_, other->price_);
  swap(depth_, other->depth_);
  swap(side_, other->side_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata PricePointProto::GetMetadata() const {
  protobuf_shared_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_shared_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void SpreadProto::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SpreadProto::kSpreadFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SpreadProto::SpreadProto()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_shared_2eproto::scc_info_SpreadProto.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:proto.SpreadProto)
}
SpreadProto::SpreadProto(const SpreadProto& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  spread_ = from.spread_;
  // @@protoc_insertion_point(copy_constructor:proto.SpreadProto)
}

void SpreadProto::SharedCtor() {
  spread_ = 0;
}

SpreadProto::~SpreadProto() {
  // @@protoc_insertion_point(destructor:proto.SpreadProto)
  SharedDtor();
}

void SpreadProto::SharedDtor() {
}

void SpreadProto::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* SpreadProto::descriptor() {
  ::protobuf_shared_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_shared_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const SpreadProto& SpreadProto::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_shared_2eproto::scc_info_SpreadProto.base);
  return *internal_default_instance();
}


void SpreadProto::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.SpreadProto)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  spread_ = 0;
  _internal_metadata_.Clear();
}

bool SpreadProto::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:proto.SpreadProto)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // float spread = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(13u /* 13 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &spread_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:proto.SpreadProto)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:proto.SpreadProto)
  return false;
#undef DO_
}

void SpreadProto::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:proto.SpreadProto)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // float spread = 1;
  if (this->spread() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(1, this->spread(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:proto.SpreadProto)
}

::google::protobuf::uint8* SpreadProto::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:proto.SpreadProto)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // float spread = 1;
  if (this->spread() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(1, this->spread(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto.SpreadProto)
  return target;
}

size_t SpreadProto::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:proto.SpreadProto)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // float spread = 1;
  if (this->spread() != 0) {
    total_size += 1 + 4;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SpreadProto::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:proto.SpreadProto)
  GOOGLE_DCHECK_NE(&from, this);
  const SpreadProto* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const SpreadProto>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:proto.SpreadProto)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:proto.SpreadProto)
    MergeFrom(*source);
  }
}

void SpreadProto::MergeFrom(const SpreadProto& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:proto.SpreadProto)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.spread() != 0) {
    set_spread(from.spread());
  }
}

void SpreadProto::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:proto.SpreadProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SpreadProto::CopyFrom(const SpreadProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:proto.SpreadProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SpreadProto::IsInitialized() const {
  return true;
}

void SpreadProto::Swap(SpreadProto* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SpreadProto::InternalSwap(SpreadProto* other) {
  using std::swap;
  swap(spread_, other->spread_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata SpreadProto::GetMetadata() const {
  protobuf_shared_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_shared_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void UUID::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int UUID::kUUIDFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

UUID::UUID()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_shared_2eproto::scc_info_UUID.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:proto.UUID)
}
UUID::UUID(const UUID& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  uuid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.uuid().size() > 0) {
    uuid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.uuid_);
  }
  // @@protoc_insertion_point(copy_constructor:proto.UUID)
}

void UUID::SharedCtor() {
  uuid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

UUID::~UUID() {
  // @@protoc_insertion_point(destructor:proto.UUID)
  SharedDtor();
}

void UUID::SharedDtor() {
  uuid_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void UUID::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* UUID::descriptor() {
  ::protobuf_shared_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_shared_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const UUID& UUID::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_shared_2eproto::scc_info_UUID.base);
  return *internal_default_instance();
}


void UUID::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.UUID)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  uuid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool UUID::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:proto.UUID)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string UUID = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_uuid()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->uuid().data(), static_cast<int>(this->uuid().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "proto.UUID.UUID"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:proto.UUID)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:proto.UUID)
  return false;
#undef DO_
}

void UUID::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:proto.UUID)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string UUID = 1;
  if (this->uuid().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->uuid().data(), static_cast<int>(this->uuid().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "proto.UUID.UUID");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->uuid(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:proto.UUID)
}

::google::protobuf::uint8* UUID::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:proto.UUID)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string UUID = 1;
  if (this->uuid().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->uuid().data(), static_cast<int>(this->uuid().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "proto.UUID.UUID");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->uuid(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto.UUID)
  return target;
}

size_t UUID::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:proto.UUID)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string UUID = 1;
  if (this->uuid().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->uuid());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void UUID::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:proto.UUID)
  GOOGLE_DCHECK_NE(&from, this);
  const UUID* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const UUID>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:proto.UUID)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:proto.UUID)
    MergeFrom(*source);
  }
}

void UUID::MergeFrom(const UUID& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:proto.UUID)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.uuid().size() > 0) {

    uuid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.uuid_);
  }
}

void UUID::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:proto.UUID)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void UUID::CopyFrom(const UUID& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:proto.UUID)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool UUID::IsInitialized() const {
  return true;
}

void UUID::Swap(UUID* other) {
  if (other == this) return;
  InternalSwap(other);
}
void UUID::InternalSwap(UUID* other) {
  using std::swap;
  uuid_.Swap(&other->uuid_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata UUID::GetMetadata() const {
  protobuf_shared_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_shared_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::proto::MarketRequestProto* Arena::CreateMaybeMessage< ::proto::MarketRequestProto >(Arena* arena) {
  return Arena::CreateInternal< ::proto::MarketRequestProto >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::proto::PricePointProto* Arena::CreateMaybeMessage< ::proto::PricePointProto >(Arena* arena) {
  return Arena::CreateInternal< ::proto::PricePointProto >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::proto::SpreadProto* Arena::CreateMaybeMessage< ::proto::SpreadProto >(Arena* arena) {
  return Arena::CreateInternal< ::proto::SpreadProto >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::proto::UUID* Arena::CreateMaybeMessage< ::proto::UUID >(Arena* arena) {
  return Arena::CreateInternal< ::proto::UUID >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
